package com.easemytrip.dto;

import lombok.Builder;
import lombok.Data;
import java.util.List;

@Data
@Builder
public class Itinerary {
    private String source;
    private String destination;
    private String startDate;
    private String endDate;
    private String budget;
    private String interests;
    private String allergies;
    private String medications;
    private String healthConditions;
    private List<String> days;// Each day's plan as generated by AI
}